# Generated by Django 3.2.6 on 2021-09-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("collection", "0001_initial"),
        ("collection", "0002_alter_collection_user"),
        ("collection", "0003_remove_collection_name"),
        ("collection", "0004_alter_collection_user"),
    ]

    initial = True

    dependencies = [
        ("song", "0002_song_blocked"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.ManyToManyField(blank=True, null=True, to="song.Song")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
