# Generated by Django 3.2.6 on 2021-09-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("collection", "0002_alter_collection_user")]

    operations = [migrations.RemoveField(model_name="collection", name="name")]
