# Generated by Django 3.2.6 on 2021-09-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("album", "0001_initial"), ("album", "0002_remove_album_author")]

    initial = True

    dependencies = [("author", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
            ],
        )
    ]
