# Generated by Django 3.2.6 on 2021-09-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("album", "0001_initial")]

    operations = [migrations.RemoveField(model_name="album", name="author")]
