# Generated by Django 3.2.6 on 2021-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("user", "0002_customuser_favourite_genre"),
        ("user", "0003_customuser_favourite_author"),
    ]

    dependencies = [
        ("author", "0001_initial"),
        ("user", "0001_squashed_0003_customuser_group"),
        ("genre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favourite_genre",
            field=models.ManyToManyField(blank=True, null=True, to="genre.Genre"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favourite_author",
            field=models.ManyToManyField(blank=True, null=True, to="author.Author"),
        ),
    ]
