# Generated by Django 3.2.6 on 2021-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genre", "0001_initial"),
        ("user", "0001_squashed_0003_customuser_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favourite_genre",
            field=models.ManyToManyField(blank=True, null=True, to="genre.Genre"),
        )
    ]
