# Generated by Django 3.2.6 on 2021-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
        ("user", "0002_customuser_favourite_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favourite_author",
            field=models.ManyToManyField(blank=True, null=True, to="author.Author"),
        )
    ]
