# Generated by Django 3.2.6 on 2021-08-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='music')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('author', models.ManyToManyField(to='author.Author')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='song.songdata', verbose_name='song')),
                ('genre', models.ManyToManyField(to='genre.Genre')),
            ],
        ),
    ]
