# Generated by Django 3.2.6 on 2021-08-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('data', models.FileField(upload_to='music')),
                ('author', models.ManyToManyField(to='author.Author')),
                ('genre', models.ManyToManyField(to='genre.Genre')),
            ],
        ),
    ]
