# Generated by Django 3.2.6 on 2021-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
