# Generated by Django 3.2.6 on 2021-08-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("song", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="song", name="blocked", field=models.BooleanField(default=False)
        )
    ]
