# Generated by Django 3.2.6 on 2021-09-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("album", "0001_initial"), ("song", "0002_song_blocked")]

    operations = [
        migrations.AddField(
            model_name="song",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="album.album",
            ),
        )
    ]
