# Generated by Django 3.2.6 on 2021-08-26 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("song", "0003_blockedsong")]

    operations = [
        migrations.AlterField(
            model_name="blockedsong",
            name="song",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="song.song"
            ),
        )
    ]
